//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSAC.Modelo.modulo_cliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTEESTABLECIMIENTO
    {
        public CLIENTEESTABLECIMIENTO()
        {
            this.CLIENTEESTIMAGEN = new HashSet<CLIENTEESTIMAGEN>();
            this.CLIENTELOTE = new HashSet<CLIENTELOTE>();
        }
    
        public int idEstablecimiento { get; set; }
        public string nombre { get; set; }
        public string Cliente { get; set; }
        public Nullable<decimal> SupTotal { get; set; }
        public Nullable<decimal> SupUtil { get; set; }
        public Nullable<int> CantidadLotes { get; set; }
        public Nullable<int> CantidadLotesSegim { get; set; }
        public string Lugar { get; set; }
        public string Observaciones { get; set; }
    
        public virtual CLIENTE CLIENTE1 { get; set; }
        public virtual LUGAR LUGAR1 { get; set; }
        public virtual ICollection<CLIENTEESTIMAGEN> CLIENTEESTIMAGEN { get; set; }
        public virtual ICollection<CLIENTELOTE> CLIENTELOTE { get; set; }
    }
}
