//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSAC.Modelo.modulo_cliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTELOTE
    {
        public CLIENTELOTE()
        {
            this.CLIENTELOTEIMAGEN = new HashSet<CLIENTELOTEIMAGEN>();
        }
    
        public int idLote { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Establecimiento { get; set; }
        public Nullable<decimal> SupTotal { get; set; }
        public Nullable<decimal> SupUtil { get; set; }
        public string TipoSuelo { get; set; }
        public string TipoRelieve { get; set; }
        public string GeoLatitud { get; set; }
        public string GeoLongitud { get; set; }
        public string Observaciones { get; set; }
    
        public virtual CLIENTEESTABLECIMIENTO CLIENTEESTABLECIMIENTO { get; set; }
        public virtual ICollection<CLIENTELOTEIMAGEN> CLIENTELOTEIMAGEN { get; set; }
    }
}
