//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSAC.Modelo.modulo_cliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.CLIENTECONTACTO = new HashSet<CLIENTECONTACTO>();
            this.CLIENTEESTABLECIMIENTO = new HashSet<CLIENTEESTABLECIMIENTO>();
            this.CLIENTENOCONFORMIDAD = new HashSet<CLIENTENOCONFORMIDAD>();
        }
    
        public string Cuenta { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> CondicionIVA { get; set; }
        public string CUIT { get; set; }
        public Nullable<int> CondicionGanancia { get; set; }
        public string NumeroGanancia { get; set; }
        public string NumeroJubilacion { get; set; }
        public Nullable<int> CondicionIngBru { get; set; }
        public string NumeroIngBru { get; set; }
        public string CBU { get; set; }
        public string GananciaCodigo { get; set; }
        public Nullable<System.DateTime> FechaVtoGanancia { get; set; }
        public string Nombre { get; set; }
        public string NombreFantasia { get; set; }
        public string Domicilio { get; set; }
        public Nullable<int> NroDomicilio { get; set; }
        public string Localidad { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public string Pais { get; set; }
        public string Zona { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaUltVta { get; set; }
        public Nullable<System.DateTime> FechaDetectado { get; set; }
        public Nullable<int> OrigenCliente { get; set; }
    
        public virtual CLIENTECONDGANANCIAS CLIENTECONDGANANCIAS { get; set; }
        public virtual CLIENTECONDICIONIVA CLIENTECONDICIONIVA { get; set; }
        public virtual CLIENTECONDINGRBRU CLIENTECONDINGRBRU { get; set; }
        public virtual CLIENTEESTADO CLIENTEESTADO { get; set; }
        public virtual CLIENTEORIGEN CLIENTEORIGEN { get; set; }
        public virtual LOCALIDAD LOCALIDAD1 { get; set; }
        public virtual PAIS PAIS1 { get; set; }
        public virtual ZONA ZONA1 { get; set; }
        public virtual ICollection<CLIENTECONTACTO> CLIENTECONTACTO { get; set; }
        public virtual ICollection<CLIENTEESTABLECIMIENTO> CLIENTEESTABLECIMIENTO { get; set; }
        public virtual ICollection<CLIENTENOCONFORMIDAD> CLIENTENOCONFORMIDAD { get; set; }
    }
}
