//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSAC.Modelo.modulo_cliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTEESTADO
    {
        public CLIENTEESTADO()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
        }
    
        public int idEstadoCliente { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
    }
}
