//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSAC.Modelo.modulo_cliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO
    {
        public DEPARTAMENTO()
        {
            this.LOCALIDAD = new HashSet<LOCALIDAD>();
        }
    
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string CodigoOncca { get; set; }
        public Nullable<int> Exportado { get; set; }
    
        public virtual ICollection<LOCALIDAD> LOCALIDAD { get; set; }
    }
}
