//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSAC.Modelo.modulo_cliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALIDAD
    {
        public LOCALIDAD()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.LUGAR = new HashSet<LUGAR>();
        }
    
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string CodigoOncca { get; set; }
        public Nullable<int> Exportado { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO1 { get; set; }
        public virtual PROVINCIA PROVINCIA1 { get; set; }
        public virtual ICollection<LUGAR> LUGAR { get; set; }
    }
}
