//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSAC.Modelo.modulo_cliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUGAR
    {
        public LUGAR()
        {
            this.CLIENTEESTABLECIMIENTO = new HashSet<CLIENTEESTABLECIMIENTO>();
        }
    
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> KilometrosAsfalto { get; set; }
        public Nullable<decimal> KilometrosTierra { get; set; }
        public string Localidad { get; set; }
        public string Domicilio { get; set; }
        public Nullable<int> NroDomicilio { get; set; }
        public string Pais { get; set; }
        public string PuertoOncca { get; set; }
        public string Cliente { get; set; }
        public string GeoLatitud { get; set; }
        public string GeoLongitud { get; set; }
    
        public virtual ICollection<CLIENTEESTABLECIMIENTO> CLIENTEESTABLECIMIENTO { get; set; }
        public virtual LOCALIDAD LOCALIDAD1 { get; set; }
        public virtual PAIS PAIS1 { get; set; }
    }
}
