//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSAC.Modelo.modulo_cliente
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSACEntities : DbContext
    {
        public SSACEntities()
            : base("name=SSACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ARTICULOS> ARTICULOS { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<CLIENTECONDGANANCIAS> CLIENTECONDGANANCIAS { get; set; }
        public DbSet<CLIENTECONDICIONIVA> CLIENTECONDICIONIVA { get; set; }
        public DbSet<CLIENTECONDINGRBRU> CLIENTECONDINGRBRU { get; set; }
        public DbSet<CLIENTECONTACTO> CLIENTECONTACTO { get; set; }
        public DbSet<CLIENTEESTABLECIMIENTO> CLIENTEESTABLECIMIENTO { get; set; }
        public DbSet<CLIENTEESTADO> CLIENTEESTADO { get; set; }
        public DbSet<CLIENTEESTIMAGEN> CLIENTEESTIMAGEN { get; set; }
        public DbSet<CLIENTELOTE> CLIENTELOTE { get; set; }
        public DbSet<CLIENTELOTEIMAGEN> CLIENTELOTEIMAGEN { get; set; }
        public DbSet<CLIENTENOCONFORMIDAD> CLIENTENOCONFORMIDAD { get; set; }
        public DbSet<CLIENTEORIGEN> CLIENTEORIGEN { get; set; }
        public DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public DbSet<LOCALIDAD> LOCALIDAD { get; set; }
        public DbSet<LUGAR> LUGAR { get; set; }
        public DbSet<PAIS> PAIS { get; set; }
        public DbSet<PROVINCIA> PROVINCIA { get; set; }
        public DbSet<ZONA> ZONA { get; set; }
    }
}
